### PR TITLE
Updates to latest Alpine version

### PR DESCRIPTION
**Pull request by lucasvanlierop**
Apart from updating the base image every now and then, would be possible to change to a scheduled automated build at Docker hub to get the latest updates?

### CODE REVIEW

**Review by fruitl00p — APPROVED** [review]
Should be good!

**Comment by fruitl00p** [comment]
The build on docker is automated based on commits (per branch) thus any new build would automatically be triggerd.

we could consider tagging the various Alpine versions / SSHd versions, but that seems overkill. Thus updates like yours (🙌) are imho the way to go...

(or am i missing something?)

**Comment by lucasvanlierop** [comment]
Thanks for merging so fast! Just did a quick check on the rebuild, Docker Hub (still?) doesn't seem to support a cron like automatic rebuild. It would be possible to [trigger a from a remote system](https://docs.docker.com/docker-hub/builds/#remote-build-triggers) e.g. Travis CI. Might be nice in case there are no changes to the `Dockerfile` for a while and a security update for SSH is necessary. For now I'll keep bumping Alpine versions ;-)

**Comment by fruitl00p** [comment]
@lucasvanlierop But would the docker build service pull the `latest` apline:3.x build ? Or would it reuse its own cache specific for this repo?
(and if the latter, the automatic build wouldn't update the image at all...)

We could schedule a 'simple' monthly cron job to hit the trigger... but that seems hackish and weird...

**Comment by lucasvanlierop** [comment]
Sorry I missed your reply. I meant pulling the latest version of the current version of the base image. This is assuming when a bug in SSH is found all recent Alpine versions receive an update so for example I imagine this happening:

day 1: image is built on Alpine 3.7
day 2: vulnerability is discovered in SSH -> applications using it are now vulnerable too
day 3: Fix is backported in Alpine 3.7
day x: scheduled rebuilds image based on latest Alpine 3.7 -> applications using it are now safe again (assuming they pull the docker-tunnel image before using it.)

day

**Comment by fruitl00p** [comment]
@lucasvanlierop So if i understand correctly, just triggering the rebuild (without actual changes to the repo) would fully pull, rebuild and publish a clean, new build of the image?

It's worth a shot ;)

**Comment by lucasvanlierop** [comment]
I'm not sure, but it would make sense. This must be a 'problem' many projects have right?

**Comment by fruitl00p** [comment]
I would expect other projects to indeed have the same issue. I'll just re-build once in a while for now... :)

**Comment by lucasvanlierop** [comment]
:+1: Tnx

**Pull request merged**
